### ISSUE TITLE
Pád při startu 

### ISSUE THREAD

**Issue by aditucz** [b3da-cz/rn-nyx-app#10]
Jednou až tak dvakrát třikrát za den mi app zhavaruje při startu. 
Chybová hláška co mi ukáže v detailu telefon (Xiaomi Redmi 4x global, android 7.1.2):

java.lang.RuntimeException: Unable to start activity ComponentInfo{net.b3da.nnn/net.b3da.nnn.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2723)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:566)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)
	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:196)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:287)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:44)
	at net.b3da.nnn.MainActivity.onCreate(MainActivity.java:20)
	at android.app.Activity.performCreate(Activity.java:6857)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2676)
	... 9 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
	... 21 more
Caused by: java.lang.IllegalStateException: Screen fragments should never be restored. Follow instructions from https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 to properly configure your main activity.
	at com.swmansion.rnscreens.ScreenFragment.<init>(ScreenFragment.java:42)
	... 24 more

**Comment by aditucz** [comment]
V. 0.1.18
